### ISSUE TITLE
lack of double -- in wsub commands in examples

### ISSUE THREAD

**Issue by mselwa** [gjbex/worker-ng#20]
Hi,
Most of the examples have a typo in README:

failures: wsub  --cluster=genius  --batch=failures.slurm  -data=data.csv
while it should be wsub  --cluster=genius  --batch=failures.slurm  --data=data.csv

python_sum: wsub  --cluster=genius  --batch=sum.slurm  -data=data.csv
it should be wsub  --cluster=genius  --batch=sum.slurm  --data=data.csv

simple: is ok

wc:  wsub  --batch=wc.slurm  -array=1-100
should be  wsub  --batch=wc.slurm  --array=1-100

**Comment by gjbex** [comment]
@mselwa Thanks, all fixed.

**Comment by gjbex** [comment]
Done
