### ISSUE TITLE
Make sure python3 is used

### ISSUE THREAD

**Issue by stevenvdb** [gjbex/worker-ng#9]
On a genius login node, the following fails:
```
vsc33716@tier2-p-login-2:~$ module load worker-ng
vsc33716@tier2-p-login-2:~$ wsub --help
  File "/vsc-hard-mounts/leuven-apps/rocky8/skylake/2021a/software/worker-ng/1.0-GCCcore-10.3.0/bin/../lib/wsub.py", line 20
    msg=f'"{config_path}" not found')
                                   ^
SyntaxError: invalid syntax
vsc33716@tier2-p-login-2:~$ python --version
Python 2.7.18
```
I am pretty sure that the problem is our `python` command still gives you `python2`. Could we adapt the shebang of the Python scripts to `#!/usr/bin/env python3`?

I also asked to make `python3` the default python version on Genius; if that is done, the proposed change to the shebang is not necessary (but might still be useful).

**Comment by gjbex** [comment]
Resolved by changing dependencies.
